language: node_js
node_js:
  - "6.11.0" 

before_script:
  - npm install

cache:
  directories:
    - "node_modules" 
sudo: false
dist: trusty

script: 
  - npm test

after_success:
  - npm run coveralls-report
  - npm run codeclimate-report
 
