language: node_js
node_js:
    - "6.11.0" 
addons:
    code_climate:
      repo_token: 11a896d0e9347e467013fa105f49273ab8da79840a60a363143e8da1ad91980e         
before_script:
  - npm install
  - npm install codeclimate-test-reporter istanbul -g
cache:
  directories:
    - "node_modules"     
script: 
  - npm test
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
