language: node_js
node_js:
    - "6.11.0" 
env:
 - CODECLIMATE_REPO_TOKEN: 11a896d0e9347e467013fa105f49273ab8da79840a60a363143e8da1ad91980e
 - DB=weconnect

before_script:
  - npm install
  - psql -c 'create database weconnect;' -U olatunji
cache:
  directories:
    - "node_modules" 
services:
  - postgresql
        
script: 
  - npm test

after_success:
  - npm run coveralls-report
  - npm run codeclimate-report
 
