module.exports = {
  'signing up from the home page': (browser) => {
    browser
      .url('http://localhost:3000')
      .waitForElementVisible('body', 1000)
      .pause(1000)
      .waitForElementVisible('.banner', 2000)
      .pause(1000)
      .waitForElementVisible('.btn-large', 1000)
      .pause(1000)
      .waitForElementVisible('.category-header', 2000)
      .click('.btn-large')
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/signup')
      .pause(1000)
      .setValue('input[name=firstname]', 'alpha')
      .pause(1000)
      .setValue('input[name=lastname]', 'ogilo')
      .pause(1000)
      .setValue('input[name=username]', 'alapha')
      .pause(1000)
      .setValue('input[name=email]', 'alpha@ogi.com')
      .pause(1000)
      .setValue('input[name=password]', 'alphaogilo')
      .pause(1000)
      .setValue('input[name=confirmPassword]', 'alphaogilo')
      .click('.form-btn')
      .pause(1000)
      .waitForElementVisible('.newuser', 1000)
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/welcome')
      .pause(1000)
      .waitForElementVisible('.welcome-btn', 1000)
      .pause(1000)
      .click('.welcome-btn')
      .waitForElementVisible('.search-section', 2000)
      .pause(1000)
      .waitForElementVisible('.select-borders', 2000)
      .assert.urlEquals('http://localhost:3000/businesses')
      .waitForElementVisible('.search-section', 1000)
      .waitForElementVisible('#logout', 1000)
      .pause(1000)
      .click('#logout')
      .pause(1000);
  },
  'attempt signing up with unacceptable parameters': (browser) => {
    browser
      .url('http://localhost:3000')
      .pause(1000)
      .waitForElementVisible('body', 1000)
      .waitForElementVisible('.banner', 2000)
      .pause(1000)
      .waitForElementVisible('.btn-large', 1000)
      .pause(1000)
      .waitForElementVisible('.category-header', 2000)
      .click('.btn-large')
      .pause(4000)
      .assert.urlEquals('http://localhost:3000/signup')
      .setValue('input[name=firstname]', 'someone')
      .setValue('input[name=lastname]', 'somebody')
      .setValue('input[name=username]', 'qsomeone')
      .setValue('input[name=email]', 'qsome@one.com')
      .setValue('input[name=password]', 'som')
      .setValue('input[name=confirmPassword]', 'som')
      .click('.form-btn')
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/signup')
      .pause(1000)
      .waitForElementVisible('.error-box', 1000)
      .pause(2000);
  },
  'flip from signup form to signin': (browser) => {
    browser
      .url('http://localhost:3000')
      .waitForElementVisible('body', 1000)
      .pause(1000)
      .waitForElementVisible('.banner', 2000)
      .pause(1000)
      .waitForElementVisible('.btn-large', 1000)
      .pause(1000)
      .waitForElementVisible('.category-header', 2000)
      .click('.btn-large')
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/signup')
      .waitForElementVisible('.form-jacket', 2000)
      .pause(1000)
      .waitForElementVisible('.auth-hover', 2000)
      .click('.auth-hover')
      .pause(1000)
      .waitForElementVisible('#loginForm', 2000)
      .assert.urlEquals('http://localhost:3000/login')
      .pause(1000)
      .click('.auth-hover')
      .waitForElementVisible('.form-jacket', 2000)
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/signup')
      .pause(2000);
  },
  'login with wrong parameters': (browser) => {
    browser
      .url('http://localhost:3000/login')
      .waitForElementVisible('.form-jacket', 1000)
      .waitForElementVisible('#loginForm', 2000)
      .pause(1000)
      .waitForElementVisible('.form-btn', 2000)
      .setValue('input[name=username]', 'random')
      .pause(1000)
      .setValue('input[name=password]', 'random')
      .click('.form-btn')
      .pause(4000)
      .assert.urlEquals('http://localhost:3000/login')
      .pause(1000)
      .waitForElementVisible('#loginErrors', 2000)
      .pause(2000);
  },
  'login with correct parameters': (browser) => {
    browser
      .url('http://localhost:3000/login')
      .pause(1000)
      .waitForElementVisible('.form-jacket', 1000)
      .waitForElementVisible('#loginForm', 2000)
      .waitForElementVisible('.form-btn', 2000)
      .pause(1000)
      .setValue('input[name=username]', 'alapha')
      .setValue('input[name=password]', 'alphaogilo')
      .pause(1000)
      .click('.form-btn')
      .waitForElementVisible('.banner', 2000)
      .assert.urlEquals('http://localhost:3000/')
      .pause(1000)
      .waitForElementVisible('#logout', 1000)
      .click('#logout')
      .pause(2000)
      .end();
  }
};