module.exports = {
  'A user signs in an creates a business': (browser) => {
    browser
      .url('http://localhost:3000/login')
      .waitForElementVisible('.form-jacket', 1000)
      .waitForElementVisible('#loginForm', 2000)
      .pause(1000)
      .waitForElementVisible('.form-btn', 2000)
      .pause(1000)
      .setValue('input[name=username]', 'alapha')
      .pause(1000)
      .setValue('input[name=password]', 'alphaogilo')
      .click('.form-btn')
      .waitForElementVisible('.banner', 2000)
      .pause(1000)
      .assert.urlEquals('http://localhost:3000/')
      .waitForElementVisible('#userProfile', 2000)
      .click('#userProfile')
      .pause(1000)
      .waitForElementVisible('.dashboard', 1000)
      .waitForElementVisible('#addBusiness', 1000)
      .pause(1000)
      .waitForElementVisible('#updateProfile', 1000)
      .click('#addBusiness')
      .pause(1000)
      .waitForElementVisible('#businessReg', 2000)
      .click('#businessReg')
      .pause(1000)
      .waitForElementVisible('.business-form', 3000)
      .pause(1000)
      .setValue('input[name=name]', 'My first Business')
      .pause(6000)
      .setValue('select[name=state]', 'lagos')
      .pause(2000)
      .setValue('select[name=category]', 'fashion')
      .pause(2000)
      .setValue('textarea[name=address]', 'The first road on the mildoe way')
      .pause(2000)
      .setValue('input[name=email]', 'first@business.com')
      .pause(2000)
      .setValue('input[name=phone]', '123456765432')
      .pause(2000)
      .setValue('input[name=city]', 'London')
      .pause(2000)
      .setValue('textarea[name=about]', 'Tell me this and thabb hhgfdfgt tell me this and that yell me that wety ewr wey wey weyt wey wwdff')
      .pause(2000)
      .waitForElementVisible('.btn-large', 5000)
      .click('.btn-large')
      .pause(2000)
      .waitForElementVisible('#addBusiness', 3000)
      .waitForElementVisible('#updateProfile', 3000)
      .pause(2000)
      .waitForElementVisible('#myBusiness', 3000)
      .pause(2000)
      .assert.urlEquals('http://localhost:3000/userProfile')
      .pause(2000);
  },
  'A user views a business': (browser) => {
    browser
      .url('http://localhost:3000/businesses')
      .waitForElementVisible('.search-section', 2000)
      .pause(2000)
      .waitForElementVisible('.business-card-label', 2000)
      .pause(2000)
      .waitForElementVisible('.card-button', 2000)
      .pause(2000)
      .click('.card-button')
      .waitForElementVisible('.business-hero', 2000)
      .pause(2000)
      .waitForElementVisible('.business-body', 2000)
      .pause(2000)
      .waitForElementVisible('.business-contact-body', 2000)
      .assert.urlEquals('http://localhost:3000/businesses/1')
      .pause(2000)
      .pause(2000)
      .setValue('textarea[name=message]', 'The is very very very awesome mhenn!')
      .pause(2000)
      .waitForElementVisible('.form-btn', 2000)
      .click('.form-btn')
      .waitForElementVisible('#reviewCard', 2000)
      .pause(2000)
      .waitForElementVisible('#editReviewPen', 2000)
      .click('#editReviewPen')
      .pause(2000)
      .waitForElementVisible('#cancelReviewUpdate', 2000)
      .click('#cancelReviewUpdate')
      .pause(2000)
      .waitForElementVisible('#editReviewPen', 2000);
  },
  'Updating a business': (browser) => {
    browser
      .url('http://localhost:3000/userProfile')
      .waitForElementVisible('#addBusiness', 2000)
      .pause(2000)
      .waitForElementVisible('#updateProfile', 2000)
      .waitForElementVisible('.manageBusiness', 2000)
      .click('.manageBusiness')
      .pause(2000)
      .assert.urlEquals('http://localhost:3000/manageBusiness/1')
      .waitForElementVisible('.btn-edit', 2000)
      .pause(2000)
      .click('.btn-edit')
      .pause(2000)
      .assert.urlEquals('http://localhost:3000/businessUpdate/1')
      .waitForElementVisible('.business-form', 2000)
      .pause(2000)
      .setValue('input[name=name]', '')
      .setValue('input[name=name]', 'here!')
      .pause(2000)
      .waitForElementVisible('.form-btn', 2000)
      .click('.form-btn')
      .pause(2000)
      .waitForElementVisible('.business-hero', 2000)
      .pause(2000)
      .waitForElementVisible('.business-body', 2000)
      .pause(2000)
      .waitForElementVisible('.business-contact-body', 2000)
      .assert.urlEquals('http://localhost:3000/businesses/1')
      .pause(2000);
  }
};