export const ATTEMPT = 'ATTEMPT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const BAD_REQUEST = 'BAD_REQUEST';

export const CONFLICT = 'CONFLICT';

export const PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';

export const FAILED_SIGNIN = 'FAILED_SIGNIN';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const ON_BOARDING_SUCCESS = 'ON_BOARDING_SUCCESS';

export const UNAUTHENTICATED = 'UNAUTHENTICATED';

export const AUTHENTICATED = 'AUTHENTICATED';

export const FETCHED_BUSINESSES = 'FETCHED_BUSINESSES';

export const FETCHED_BUSINESS = 'FETCHED_BUSINESS';

export const FOUND_MY_BUSINESSES = 'FOUND_MY_BUSINESSES';

export const GOT_NO_BUSINESSES = 'GOT_NO_BUSINESSES';

export const NOT_FOUND = 'NOT_FOUND';

export const FORBIDDEN = 'FORBIDDEN';

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export const STOP_SPINNER = 'STOP_SPINNER';

export const SUCCESS = 'SUCCESS';

