export const ATTEMPT = 'ATTEMPT';

export const SIGNUP_REQUEST_SUCCESS = 'SIGNUP_REQUEST_SUCCESS';

export const SIGNIN_REQUEST_SUCCESS = 'SIGNIN_REQUEST_SUCCESS';

export const ON_BOARDING_SUCCESS = 'ON_BOARDING_SUCCESS';

export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';

export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS';

export const SIGNIN_REQUEST_ERROR = 'SIGNIN_REQUEST_ERROR';

export const SIGNUP_REQUEST_ERROR = 'SIGNUP_REQUEST_ERROR';

export const FIND_MY_BUSINESSES_SUCCESS = 'FIND_MY_BUSINESSES_SUCCESS';

export const FIND_MY_BUSINESSES_FAILED = 'FIND_MY_BUSINESSES_FAILED';

export const FETCH_BUSINESS_FAILED = 'FETCH_BUSINESS_FAILED';

export const MAKING_AUTH_REQUEST = 'MAKING_AUTH_REQUEST';

export const MAKING_BUSINESS_REQUEST = 'MAKING_BUSINESS_REQUEST';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REGISTER_BUSINESS_FAILED = 'REGISTER_BUSINESS_FAILED';

export const UPDATE_BUSINESS_FAILED = 'UPDATE_BUSINESS_FAILED';

export const DELETE_BUSINESS_FAILED = 'DELETE_BUSINESS_FAILED';
